version: '3'

services:
  relay:
    container_name: "relay"
    image: ghcr.io/jffp113/algorand
    build:
      context: ./../
      dockerfile: ./docker/Dockerfile
    entrypoint: []
    environment:
      - SIGNERNODE=signernode-1:8080
      - GROUPSIG=0
    command: |
      bash -c "
        chmod 777 ./installer/genesis/jorgenetwork/relay/start.sh
        ./installer/genesis/jorgenetwork/relay/start.sh
      "

  peer1:
    container_name: "peer1"
    image: ghcr.io/jffp113/algorand
    entrypoint: []
    ports:
      - "4001:4001"
    environment:
      - SIGNERNODE=signernode-2:8080
      - BOOTSTRAP=relay
      - GROUPSIG=0
    command: |
      bash -c "
        chmod 777 ./installer/genesis/jorgenetwork/participant1/start.sh
        ./installer/genesis/jorgenetwork/participant1/start.sh
      "
    depends_on:
      - relay

  peer2:
    container_name: "peer2"
    image: ghcr.io/jffp113/algorand
    entrypoint: []
    ports:
      - "4002:4001"
    environment:
      - SIGNERNODE=signernode-3:8080
      - BOOTSTRAP=relay
      - GROUPSIG=0
    command: |
      bash -c "
        chmod 777 ./installer/genesis/jorgenetwork/participantGeneric/start.sh
        ./installer/genesis/jorgenetwork/participantGeneric/start.sh
      "
    depends_on:
      - relay

  peer3:
    container_name: "peer3"
    image: ghcr.io/jffp113/algorand
    entrypoint: []
    ports:
      - "4003:4001"
    environment:
      - SIGNERNODE=signernode-4:8080
      - GROUPSIG=0
      - BOOTSTRAP=relay
    command: |
      bash -c "
        chmod 777 ./installer/genesis/jorgenetwork/participantGeneric/start.sh
        ./installer/genesis/jorgenetwork/participantGeneric/start.sh
      "
    depends_on:
      - relay

  peer4:
    container_name: "peer4"
    image: ghcr.io/jffp113/algorand
    entrypoint: []
    ports:
      - "4004:4001"
    environment:
      - SIGNERNODE=signernode-5:8080
      - GROUPSIG=0
      - BOOTSTRAP=relay
    command: |
      bash -c "
        chmod 777 ./installer/genesis/jorgenetwork/participantGeneric/start.sh
        ./installer/genesis/jorgenetwork/participantGeneric/start.sh
      "
    depends_on:
      - relay

networks:
  default:
    external:
      name: networkThesis