version: '3'

services:
  relay:
    container_name: "relay"
    image: algorand
    build:
      context: ./../
      dockerfile: ./docker/Dockerfile
    entrypoint: []
    command: |
      bash -c "
        chmod 777 ./installer/genesis/jorgenetwork/relay/start.sh
        ./installer/genesis/jorgenetwork/relay/start.sh
      "

  peer1:
    container_name: "peer1"
    image: algorand
    entrypoint: []
    ports:
      - "4001:4001"
    command: |
      bash -c "
        chmod 777 ./installer/genesis/jorgenetwork/participant1/start.sh
        ./installer/genesis/jorgenetwork/participant1/start.sh
      "
    depends_on:
      - relay

  peer2:
    container_name: "peer2"
    image: algorand
    entrypoint: []
    command: |
      bash -c "
        chmod 777 ./installer/genesis/jorgenetwork/participantGeneric/start.sh
        ./installer/genesis/jorgenetwork/participantGeneric/start.sh
      "
    depends_on:
      - relay

  peer3:
    container_name: "peer3"
    image: algorand
    entrypoint: []
    command: |
      bash -c "
        chmod 777 ./installer/genesis/jorgenetwork/participantGeneric/start.sh
        ./installer/genesis/jorgenetwork/participantGeneric/start.sh
      "
    depends_on:
      - relay

  peer4:
    container_name: "peer4"
    image: algorand
    entrypoint: [ ]
    command: |
      bash -c "
        chmod 777 ./installer/genesis/jorgenetwork/participantGeneric/start.sh
        ./installer/genesis/jorgenetwork/participantGeneric/start.sh
      "
    depends_on:
      - relay