version: '3'


#Vars
#export SIGNERNODE_IP=localhost
#export SIGNERNODE_PORT=8080
#export GROUPSIG=1
#export PORT=1

services:
  peer:
    image: ghcr.io/jffp113/algorand
    entrypoint: []
    ports:
      - "${PORT}:4001"
    environment:
      - SIGNERNODE=${SIGNERNODE}
      - GROUPSIG=${GROUPSIG}
    command: |
      bash -c "
        chmod 777 ./installer/genesis/jorgenetwork/participant1/start.sh
        ./installer/genesis/jorgenetwork/participant1/start.sh
      "